/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelbooking.views;

import hotelbooking.controllers.CustomerTableController;
import hotelbooking.models.Customer;
import hotelbooking.models.FamilyCustomer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 *
 * @author David Ortiz
 */
public class EditCustomerView extends javax.swing.JFrame {
    
    //fields
    private CustomerTableController editController;
    private String[] currentCustomer;
    private ArrayList<Customer> customerArrayList;
    private int selectedRow;
    private boolean isItNew = false;
    
    //constructor
    public EditCustomerView(CustomerTableController _controller, int row) {
        initComponents();
        this.selectedRow = row;
        this.editController = _controller;
        this.customerArrayList = editController.getCustomerArrayList();
        
        this.currentCustomer = editController.getSelectedCustomer(row);
        
        parseCurrentHotel(this.currentCustomer);
        
        this.cancelButton.addActionListener(new CancelListener());
        this.saveButton.addActionListener(new SaveListener());
        this.deleteButton.addActionListener(new DeleteListener());
    }
    
    //for new customers
    public EditCustomerView(CustomerTableController _controller) {
        initComponents();
        this.editController = _controller;
        this.customerArrayList = editController.getCustomerArrayList();
        this.cancelButton.addActionListener(new CancelListener());
        this.saveButton.addActionListener(new SaveListener());
        this.isItNew = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        deleteButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        mainLabel = new javax.swing.JLabel();
        adultsField = new javax.swing.JTextField();
        companyField = new javax.swing.JTextField();
        lnameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        companyLabel = new javax.swing.JLabel();
        fnameField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        kidsLabel = new javax.swing.JLabel();
        kidsField = new javax.swing.JTextField();
        typeLabel = new javax.swing.JLabel();
        mainLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        deleteButton.setText("Delete");

        cancelButton.setText("Cancel");

        saveButton.setText("Save");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        mainLabel.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        mainLabel.setText("name");

        adultsField.setText("jTextField2");

        companyField.setText("jTextField3");

        lnameField.setText("jTextField1");

        jLabel1.setText("First name:");

        companyLabel.setText("Company:");

        fnameField.setText("jTextField1");

        jLabel10.setText("Last name:");

        jLabel11.setText("Adults:");

        kidsLabel.setText("Kids:");

        kidsField.setText("jTextField3");

        typeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        typeLabel.setText("Type");

        mainLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        mainLabel2.setText("Customer type:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(companyLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(adultsField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(kidsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kidsField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lnameField)
                    .addComponent(fnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(companyField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mainLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mainLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(typeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(mainLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainLabel2)
                    .addComponent(typeLabel))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(adultsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kidsLabel)
                    .addComponent(kidsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(companyLabel)
                    .addComponent(companyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EditCustomerView().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adultsField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField companyField;
    private javax.swing.JLabel companyLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField fnameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField kidsField;
    private javax.swing.JLabel kidsLabel;
    private javax.swing.JTextField lnameField;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JLabel mainLabel2;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables

    //others
    public void parseCurrentHotel(String[] selectedCustomer){
        String name = selectedCustomer[1];
        
        for(Customer c : this.customerArrayList){
            
            if(c.getLastName().equals(name)){
                
                mainLabel.setText(c.getFullName());
                fnameField.setText(c.getFirstName());
                lnameField.setText(c.getLastName());
                
                if(c.getType()=="family"){
                    typeLabel.setText("Family");
                    adultsField.setText(Integer.toString(c.getNumOfAdults()));
                    kidsField.setText(Integer.toString(c.getNumOfKids()));
                    companyField.setVisible(false);
                    companyLabel.setVisible(false);
                    
                } else if(c.getType()=="business"){
                    typeLabel.setText("Business");
                    adultsField.setText(Integer.toString(c.getAmountOfTravelers()));
                    kidsLabel.setVisible(false);
                    kidsField.setVisible(false);
                    companyField.setText(c.getCompany());
                    
                }
            }
        }
    }
    
    //listeners
    private class DeleteListener implements ActionListener{

        @Override
         public void actionPerformed(ActionEvent e) {
            int _selectedRow = EditCustomerView.this.selectedRow;
            ArrayList<Customer> temp = editController.getCustomerArrayList();
            
            temp.remove(_selectedRow);
            temp.trimToSize();
            
            
            editController.setCustomerArrayList(temp);
            editController.removeDeletedRow(_selectedRow);
            
            
            editController.setParentViewVisible();
            EditCustomerView.this.dispose();
        }
    }
    
    private class SaveListener implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            boolean success = false;
            if(companyField.isVisible()){
                if(!fnameField.getText().equals("") && !lnameField.getText().equals("") && !adultsField.getText().equals("") && !companyField.getText().equals(""))
                {
                    success = true;
                    editController.saveCustomer(EditCustomerView.this.getTypeLabel(), EditCustomerView.this.getFnameField(), EditCustomerView.this.getLnameField(), EditCustomerView.this.getAdultsField(), "", EditCustomerView.this.getCompanyField());
                    
                    } else{
                        System.out.println("One or more fields are empty");
                    }
            } //end of company isvisible
            else if(kidsField.isVisible()){
                if(!fnameField.getText().equals("") && !lnameField.getText().equals("") && !adultsField.getText().equals("")){
                    if(kidsField.getText().isEmpty()){
                        kidsField.setText("0");
                    }
                    
                    success = true;
                    editController.saveCustomer(EditCustomerView.this.getTypeLabel(), EditCustomerView.this.getFnameField(), EditCustomerView.this.getLnameField(), EditCustomerView.this.getAdultsField(), EditCustomerView.this.getKidsField(), "");
                    
                } else{
                    
                    System.out.println("One or more fields are empty");
                    
                }

            } // end of family isvisible
            
            
            if(success){
                
                editController.setParentViewVisible();
                EditCustomerView.this.dispose();
                
            }
              
        } //end of action performed 
     }
    
    private class CancelListener implements ActionListener{

          @Override
          public void actionPerformed(ActionEvent e) {
              EditCustomerView.this.editController.getCustomerDetailView().setVisible(true);
              EditCustomerView.this.dispose();
          } 
    }
    
    //accessors
    public int getSelectedRow(){
        return this.selectedRow;
    }
    public boolean getIsItNew(){
        return this.isItNew;
    }
    public String getTypeLabel(){
        return this.typeLabel.getText();
    }
    public String getFnameField(){
        return this.fnameField.getText();
    }
    public String getLnameField(){
        return this.lnameField.getText();
    }
    public String getAdultsField(){
        return this.adultsField.getText();
    }
    public String getKidsField(){
        return this.kidsField.getText();
    }
    public String getCompanyField(){
        return this.companyField.getText();
    }
    
    //mutators
    public void hideDeleteButton(){
        this.deleteButton.setVisible(false);
    }
    public void setMainLabel(String _text){
        this.mainLabel.setText(_text);
    }
    public void setFnameField(String _text){
        this.fnameField.setText(_text);
    }
    public void setLnameField(String _text){
        this.lnameField.setText(_text);
    }
    public void setTypeFamily(){
        this.typeLabel.setText("Family");
    }
    public void setTypeBusiness(){
        this.typeLabel.setText("Business");
    }
    public void setAdultsField(String _text){
        this.adultsField.setText(_text);
    }
    public void setKidsField(String _text){
        this.kidsField.setText(_text);
    }
    public void setCompanyField(String _text){
        this.companyField.setText(_text);
    }
    public void hideKidsField(){
        kidsLabel.setVisible(false);
        kidsField.setVisible(false);
    }
    public void hideCompanyField(){
        companyLabel.setVisible(false);
        companyField.setVisible(false);
    }
}
